Rails.application.routes.draw do
  post '/signup', to: 'users#create'
  post '/login', to: 'auth#login' 
  get '/users/:username',to: 'users#show' 
  post '/create/journal', to: 'journals#create' 
  get '/list/journals', to:'journals#index' 
  delete '/delete/:id', to: 'journals#destroy' 
  put '/update/:id', to: 'journals#update'
  get '/get/journal/:id', to: 'journals#show' 
  post '/add/attachment', to: 'attachments#create'
  delete '/delete/attachments/:id', to:'attachments#destroy' 
  get '/get/attachments/:journal_id', to: 'attachments#index'
  put '/journals/:id/visibility/:visibility', to: 'journals#update_visibility'
  get '/journals/:id/public_url', to: 'journals#public_url'
  get '/sharedjournal/:id', to: 'journals#sharedjournals'
  get '/get/sharedjournalbyuser', to: 'journal_permission#sharedjournals'

  get '/journals/public/:public_url', to: 'journals#public_view'
  post '/journals/:id/share/:username/:permission', to: 'journals#share'
  get '/sharedjournals/get', to: 'journal_permission#index'
  delete '/journals/:id/shareddelete/:username', to: 'journal_permission#destroy'
  put '/journals/:id/sharedupdate/:username/:permission', to: 'journal_permission#update_permission'
  delete '/journals/:id/revokeshare/:user_id', to: 'journals#revokeshare'
end